exp.practice = [
  {
    displayID: "1",
    location1: "beaker-hot-orange",
    location2: "beaker-warm-green",
    location3: "flask-hot-orange",
    location4: "flask-warm-green",
    target: "AOI1",
    competitor: "AOI2",
    condition: "boiling",
    ExpFiller: "prac",
    correctAns: "AOI1",
    list: "practice",
    instruction1: "The water | in the beaker | is boiling | and orange."
  },
  {
    displayID: "2",
    location1: "beaker-cold-orange",
    location2: "beaker-cool-green",
    location3: "flask-cold-green",
    location4: "flask-cool-orange",
    target: "AOI3",
    competitor: "AOI4",
    condition: "freezing",
    ExpFiller: "prac",
    correctAns: "AOI3",
    list: "practice",
    instruction1: "The water | in the flask | is freezing | and green."
  },
  {
    displayID: "3",
    location1: "flask-hot-green",
    location2: "flask-warm-purple",
    location3: "beaker-hot-green",
    location4: "beaker-warm-purple",
    target: "AOI2",
    competitor: "AOI1",
    condition: "60",
    ExpFiller: "prac",
    correctAns: "AOI2",
    list: "practice",
    instruction1: "The water | in the flask | is about 60 degree| and purple."
  },
  {
    displayID: "4",
    location1: "flask-cool-orange",
    location2: "flask-cold-green",
    location3: "beaker-cool-green",
    location4: "beaker-cold-orange",
    target: "AOI4",
    competitor: "AOI3",
    condition: "0",
    ExpFiller: "prac",
    correctAns: "AOI4",
    list: "practice",
    instruction1: "The water | in the beaker | is about 0 degree| and orange."
  }
];

exp.stims = [
  {
    displayID: "1",
    location1: "flask-warm-orange",
    location2: "flask-hot-green",
    location3: "beaker-warm-orange",
    location4: "beaker-hot-green",
    target: "AOI3",
    competitor: "AOI4",
    condition: "warm",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "4",
    instruction3: "The water | in the beaker | is warm | and orange.",
    trial_in_list: "1"
  },
  {
    displayID: "1",
    location1: "beaker-warm-orange",
    location2: "beaker-hot-green",
    location3: "flask-warm-orange",
    location4: "flask-hot-green",
    target: "AOI3",
    competitor: "AOI4",
    condition: "warm",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "4",
    instruction3: "The water | in the flask | is warm | and orange.",
    trial_in_list: "2"
  },
  {
    displayID: "2",
    location1: "beaker-hot-purple",
    location2: "beaker-warm-green",
    location3: "flask-hot-green",
    location4: "flask-warm-purple",
    target: "AOI2",
    competitor: "AOI1",
    condition: "warm",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "The water | in the beaker | is warm | and green.",
    trial_in_list: "3"
  },
  {
    displayID: "2",
    location1: "beaker-hot-purple",
    location2: "beaker-warm-green",
    location3: "flask-hot-green",
    location4: "flask-warm-purple",
    target: "AOI4",
    competitor: "AOI3",
    condition: "warm",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "4",
    instruction3: "The water | in the flask | is warm | and purple.",
    trial_in_list: "4"
  },
  {
    displayID: "3",
    location1: "beaker-hot-green",
    location2: "beaker-warm-orange",
    location3: "flask-hot-green",
    location4: "flask-warm-orange",
    target: "AOI1",
    competitor: "AOI2",
    condition: "boiling",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "4",
    instruction3: "The water | in the beaker | is boiling | and green.",
    trial_in_list: "5"
  },
  {
    displayID: "3",
    location1: "flask-hot-green",
    location2: "flask-warm-orange",
    location3: "beaker-hot-green",
    location4: "beaker-warm-orange",
    target: "AOI1",
    competitor: "AOI2",
    condition: "boiling",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "4",
    instruction3: "The water | in the flask | is boiling | and green.",
    trial_in_list: "6"
  },
  {
    displayID: "4",
    location1: "flask-hot-purple",
    location2: "flask-warm-orange",
    location3: "beaker-hot-orange",
    location4: "beaker-warm-purple",
    target: "AOI3",
    competitor: "AOI4",
    condition: "boiling",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "4",
    instruction3: "The water | in the beaker | is boiling | and orange.",
    trial_in_list: "7"
  },
  {
    displayID: "4",
    location1: "beaker-warm-purple",
    location2: "beaker-hot-orange",
    location3: "flask-warm-orange",
    location4: "flask-hot-purple",
    target: "AOI4",
    competitor: "AOI3",
    condition: "boiling",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "4",
    instruction3: "The water | in the flask | is boiling | and purple.",
    trial_in_list: "8"
  },
  {
    displayID: "5",
    location1: "beaker-cold-orange",
    location2: "beaker-cool-purple",
    location3: "flask-cold-orange",
    location4: "flask-cool-purple",
    target: "AOI2",
    competitor: "AOI1",
    condition: "cool",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "The water | in the beaker | is cool | and purple.",
    trial_in_list: "9"
  },
  {
    displayID: "5",
    location1: "flask-cool-purple",
    location2: "flask-cold-orange",
    location3: "beaker-cool-purple",
    location4: "beaker-cold-orange",
    target: "AOI1",
    competitor: "AOI2",
    condition: "cool",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "4",
    instruction3: "The water | in the flask | is cool | and purple.",
    trial_in_list: "10"
  },
  {
    displayID: "6",
    location1: "beaker-cold-green",
    location2: "beaker-cool-orange",
    location3: "flask-cold-orange",
    location4: "flask-cool-green",
    target: "AOI2",
    competitor: "AOI1",
    condition: "cool",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "The water | in the beaker | is cool | and orange.",
    trial_in_list: "11"
  },
  {
    displayID: "6",
    location1: "flask-cold-orange",
    location2: "flask-cool-green",
    location3: "beaker-cold-green",
    location4: "beaker-cool-orange",
    target: "AOI2",
    competitor: "AOI1",
    condition: "cool",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "The water | in the flask | is cool | and green.",
    trial_in_list: "12"
  },
  {
    displayID: "7",
    location1: "beaker-cold-orange",
    location2: "beaker-cool-green",
    location3: "flask-cold-orange",
    location4: "flask-cool-green",
    target: "AOI1",
    competitor: "AOI2",
    condition: "freezing",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "4",
    instruction3: "The water | in the beaker | is freezing | and orange.",
    trial_in_list: "13"
  },
  {
    displayID: "7",
    location1: "flask-cool-green",
    location2: "flask-cold-orange",
    location3: "beaker-cool-green",
    location4: "beaker-cold-orange",
    target: "AOI2",
    competitor: "AOI1",
    condition: "freezing",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "The water | in the flask | is freezing | and orange.",
    trial_in_list: "14"
  },
  {
    displayID: "8",
    location1: "flask-cold-purple",
    location2: "flask-cool-green",
    location3: "beaker-cold-green",
    location4: "beaker-cool-purple",
    target: "AOI3",
    competitor: "AOI4",
    condition: "freezing",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "4",
    instruction3: "The water | in the beaker | is freezing | and green.",
    trial_in_list: "15"
  },
  {
    displayID: "8",
    location1: "beaker-cool-purple",
    location2: "beaker-cold-green",
    location3: "flask-cool-green",
    location4: "flask-cold-purple",
    target: "AOI4",
    competitor: "AOI3",
    condition: "freezing",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "4",
    instruction3: "The water | in the flask | is freezing | and purple.",
    trial_in_list: "16"
  },
  {
    displayID: "9",
    location1: "flask-cold-purple",
    location2: "flask-cool-green",
    location3: "beaker-cold-green",
    location4: "beaker-cool-purple",
    target: "AOI3",
    competitor: "AOI4",
    condition: "0",
    ExpFiller: "number",
    correctAns: "AOI3",
    list: "4",
    instruction3: "The water | in the beaker | is about 0 degree| and green.",
    trial_in_list: "17"
  },
  {
    displayID: "9",
    location1: "beaker-cool-purple",
    location2: "beaker-cold-green",
    location3: "flask-cool-green",
    location4: "flask-cold-purple",
    target: "AOI4",
    competitor: "AOI3",
    condition: "0",
    ExpFiller: "number",
    correctAns: "AOI4",
    list: "4",
    instruction3: "The water | in the flask | is about 0 degree| and purple.",
    trial_in_list: "18"
  },
  {
    displayID: "10",
    location1: "beaker-cool-orange",
    location2: "beaker-cold-green",
    location3: "flask-cool-green",
    location4: "flask-cold-orange",
    target: "AOI1",
    competitor: "AOI2",
    condition: "10",
    ExpFiller: "number",
    correctAns: "AOI1",
    list: "4",
    instruction3: "The water | in the beaker | is about 10 degree| and orange.",
    trial_in_list: "19"
  },
  {
    displayID: "10",
    location1: "flask-cold-orange",
    location2: "flask-cool-green",
    location3: "beaker-cold-green",
    location4: "beaker-cool-orange",
    target: "AOI2",
    competitor: "AOI1",
    condition: "10",
    ExpFiller: "number",
    correctAns: "AOI2",
    list: "4",
    instruction3: "The water | in the flask | is about 10 degree| and green.",
    trial_in_list: "20"
  },
  {
    displayID: "11",
    location1: "flask-hot-orange",
    location2: "flask-warm-purple",
    location3: "beaker-hot-purple",
    location4: "beaker-warm-orange",
    target: "AOI4",
    competitor: "AOI3",
    condition: "60",
    ExpFiller: "number",
    correctAns: "AOI4",
    list: "4",
    instruction3: "The water | in the beaker | is about 60 degree| and orange.",
    trial_in_list: "21"
  },
  {
    displayID: "11",
    location1: "beaker-hot-purple",
    location2: "beaker-warm-orange",
    location3: "flask-hot-orange",
    location4: "flask-warm-purple",
    target: "AOI4",
    competitor: "AOI3",
    condition: "60",
    ExpFiller: "number",
    correctAns: "AOI4",
    list: "4",
    instruction3: "The water | in the flask | is about 60 degree| and purple.",
    trial_in_list: "22"
  },
  {
    displayID: "12",
    location1: "flask-hot-purple",
    location2: "flask-warm-green",
    location3: "beaker-hot-green",
    location4: "beaker-warm-purple",
    target: "AOI3",
    competitor: "AOI4",
    condition: "100",
    ExpFiller: "number",
    correctAns: "AOI3",
    list: "4",
    instruction3: "The water | in the beaker | is about 100 degree| and green.",
    trial_in_list: "23"
  },
  {
    displayID: "12",
    location1: "beaker-hot-green",
    location2: "beaker-warm-purple",
    location3: "flask-hot-purple",
    location4: "flask-warm-green",
    target: "AOI3",
    competitor: "AOI4",
    condition: "100",
    ExpFiller: "number",
    correctAns: "AOI3",
    list: "4",
    instruction3: "The water | in the flask | is about 100 degree| and purple.",
    trial_in_list: "24"
  },
  {
    displayID: "13",
    location1: "flask-cool-orange",
    location2: "flask-cool-green",
    location3: "beaker-cold-green",
    location4: "beaker-cold-orange",
    target: "AOI2",
    competitor: "AOI1",
    condition: "0",
    ExpFiller: "typeB",
    correctAns: "AOI2",
    list: "4",
    instruction3: "The water | in the flask | is about 0 degree| and green.",
    trial_in_list: "25"
  },
  {
    displayID: "14",
    location1: "flask-cool-purple",
    location2: "flask-cool-orange",
    location3: "beaker-cold-orange",
    location4: "beaker-cold-purple",
    target: "AOI1",
    competitor: "AOI2",
    condition: "0",
    ExpFiller: "typeB",
    correctAns: "AOI1",
    list: "4",
    instruction3: "The water | in the flask | is about 0 degree| and purple.",
    trial_in_list: "26"
  },
  {
    displayID: "15",
    location1: "flask-cold-green",
    location2: "flask-cold-purple",
    location3: "beaker-cool-green",
    location4: "beaker-cool-purple",
    target: "AOI3",
    competitor: "AOI4",
    condition: "10",
    ExpFiller: "typeB",
    correctAns: "AOI3",
    list: "4",
    instruction3: "The water | in the beaker | is about 10 degree| and green.",
    trial_in_list: "27"
  },
  {
    displayID: "16",
    location1: "flask-cold-green",
    location2: "flask-cold-orange",
    location3: "beaker-cool-green",
    location4: "beaker-cool-orange",
    target: "AOI4",
    competitor: "AOI3",
    condition: "10",
    ExpFiller: "typeB",
    correctAns: "AOI4",
    list: "4",
    instruction3: "The water | in the beaker | is about 10 degree| and orange.",
    trial_in_list: "28"
  },
  {
    displayID: "17",
    location1: "flask-hot-orange",
    location2: "flask-hot-purple",
    location3: "beaker-warm-purple",
    location4: "beaker-warm-orange",
    target: "AOI2",
    competitor: "AOI1",
    condition: "60",
    ExpFiller: "typeB",
    correctAns: "AOI2",
    list: "4",
    instruction3: "The water | in the flask | is about 60 degree| and purple.",
    trial_in_list: "29"
  },
  {
    displayID: "18",
    location1: "beaker-warm-green",
    location2: "beaker-warm-purple",
    location3: "flask-hot-green",
    location4: "flask-hot-purple",
    target: "AOI1",
    competitor: "AOI2",
    condition: "60",
    ExpFiller: "typeB",
    correctAns: "AOI1",
    list: "4",
    instruction3: "The water | in the beaker | is about 60 degree| and green.",
    trial_in_list: "30"
  },
  {
    displayID: "19",
    location1: "beaker-hot-orange",
    location2: "beaker-hot-green",
    location3: "flask-warm-orange",
    location4: "flask-warm-green",
    target: "AOI1",
    competitor: "AOI2",
    condition: "100",
    ExpFiller: "typeB",
    correctAns: "AOI1",
    list: "4",
    instruction3: "The water | in the beaker | is about 100 degree| and orange.",
    trial_in_list: "31"
  },
  {
    displayID: "20",
    location1: "beaker-hot-purple",
    location2: "beaker-hot-orange",
    location3: "flask-warm-orange",
    location4: "flask-warm-purple",
    target: "AOI4",
    competitor: "AOI3",
    condition: "100",
    ExpFiller: "typeB",
    correctAns: "AOI4",
    list: "4",
    instruction3: "The water | in the flask | is about 100 degree| and purple.",
    trial_in_list: "32"
  }
];
