
exp.practice = [
    { displayID: "1",
      location1: "marble_25-75_g-b",
      location2: "marble_100-0_b",
      location3: "wheel_100-0_g",
      location4: "wheel_25-75_g-b",
      target: "4",
      competitor: "3",
      condition: "prac",
      modal: "usually",
      ExpFiller: "prac",
      correctAns: "AOI4",
      list: "1",
      instruction1: "The |arrow |usually lands on |blue."
    },
    { displayID: "2",
      location1: "wheel_100-0_g",
      location2: "wheel_25-75_y-g",
      location3: "marble_25-75_g-y",
      location4: "marble_100-0_g",
      target: "3",
      competitor: "4",
      condition: "prac",
      modal: "num25",
      ExpFiller: "prac",
      correctAns: "AOI3",
      list: "1",
      instruction1: "The |marble |has a 25% chance of landing on |green."
    },
    { displayID: "3",
      location1: "wheel_100-0_b",
      location2: "wheel_100-0_y",
      location3: "marble_25-75_b-y",
      location4: "marble_25-75_y-b",
      target: "2",
      competitor: "1",
      condition: "prac",
      modal: "num100",
      ExpFiller: "prac",
      correctAns: "AOI2",
      list: "1",
      instruction1: "The |arrow |has a 100% chance of landing on |yellow."
    },
    { displayID: "4",
      location1: "marble_100-0_b",
      location2: "marble_25-75_b-g",
      location3: "wheel_100-0_g",
      location4: "wheel_25-75_b-g",
      target: "1",
      competitor: "2",
      condition: "prac",
      modal: "never",
      ExpFiller: "prac",
      correctAns: "AOI1",
      list: "1",
      instruction1: "The |marble |never lands on |green."
    }
];

exp.stims = [
  {
    displayID: "1",
    location1: "marble_100-0_b",
    location2: "marble_25-75_b-g",
    location3: "wheel_100-0_b",
    location4: "wheel_25-75_b-g",
    target: "AOI4",
    competitor: "AOI3",
    condition: "rarely",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "3",
    instruction3: "The |arrow |rarely lands on |blue.",
    trial_in_list: "1",
    variant: "V1"
  },
  {
    displayID: "1",
    location1: "marble_100-0_b",
    location2: "marble_25-75_b-g",
    location3: "wheel_100-0_b",
    location4: "wheel_25-75_b-g",
    target: "AOI1",
    competitor: "AOI2",
    condition: "always",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "3",
    instruction3: "The |marble |always lands on |blue.",
    trial_in_list: "2",
    variant: "V1"
  },
  {
    displayID: "2",
    location1: "marble_25-75_b-g",
    location2: "marble_100-0_b",
    location3: "wheel_25-75_g-b",
    location4: "wheel_100-0_g",
    target: "AOI4",
    competitor: "AOI3",
    condition: "never",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "3",
    instruction3: "The |arrow |never lands on |blue.",
    trial_in_list: "3",
    variant: "V1"
  },
  {
    displayID: "2",
    location1: "wheel_100-0_g",
    location2: "wheel_25-75_g-b",
    location3: "marble_100-0_b",
    location4: "marble_25-75_b-g",
    target: "AOI4",
    competitor: "AOI3",
    condition: "usually",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "3",
    instruction3: "The |marble |usually lands on |green.",
    trial_in_list: "4",
    variant: "V1"
  },
  {
    displayID: "4",
    location1: "wheel_25-75_b-g",
    location2: "wheel_100-0_b",
    location3: "marble_25-75_g-b",
    location4: "marble_100-0_g",
    target: "AOI2",
    competitor: "AOI1",
    condition: "always",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "3",
    instruction3: "The |arrow |always lands on |blue.",
    trial_in_list: "5",
    variant: "V1"
  },
  {
    displayID: "4",
    location1: "wheel_25-75_b-g",
    location2: "wheel_100-0_b",
    location3: "marble_25-75_g-b",
    location4: "marble_100-0_g",
    target: "AOI3",
    competitor: "AOI4",
    condition: "rarely",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "3",
    instruction3: "The |marble |rarely lands on |green.",
    trial_in_list: "6",
    variant: "V1"
  },
  {
    displayID: "5",
    location1: "wheel_100-0_b",
    location2: "wheel_25-75_b-y",
    location3: "marble_100-0_b",
    location4: "marble_25-75_b-y",
    target: "AOI2",
    competitor: "AOI1",
    condition: "usually",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "3",
    instruction3: "The |arrow |usually lands on |yellow.",
    trial_in_list: "7",
    variant: "V1"
  },
  {
    displayID: "5",
    location1: "marble_25-75_b-y",
    location2: "marble_100-0_b",
    location3: "wheel_25-75_b-y",
    location4: "wheel_100-0_b",
    target: "AOI2",
    competitor: "AOI1",
    condition: "never",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "3",
    instruction3: "The |marble |never lands on |yellow.",
    trial_in_list: "8",
    variant: "V1"
  },
  {
    displayID: "6",
    location1: "wheel_100-0_y",
    location2: "wheel_25-75_y-b",
    location3: "marble_100-0_b",
    location4: "marble_25-75_b-y",
    target: "AOI2",
    competitor: "AOI1",
    condition: "rarely",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "3",
    instruction3: "The |arrow |rarely lands on |yellow.",
    trial_in_list: "9",
    variant: "V1"
  },
  {
    displayID: "6",
    location1: "wheel_25-75_y-b",
    location2: "wheel_100-0_y",
    location3: "marble_25-75_b-y",
    location4: "marble_100-0_b",
    target: "AOI4",
    competitor: "AOI3",
    condition: "always",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "3",
    instruction3: "The |marble |always lands on |blue.",
    trial_in_list: "10",
    variant: "V1"
  },
  {
    displayID: "8",
    location1: "marble_100-0_y",
    location2: "marble_25-75_y-b",
    location3: "wheel_100-0_b",
    location4: "wheel_25-75_b-y",
    target: "AOI3",
    competitor: "AOI4",
    condition: "never",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "3",
    instruction3: "The |arrow |never lands on |yellow.",
    trial_in_list: "11",
    variant: "V1"
  },
  {
    displayID: "8",
    location1: "marble_25-75_y-b",
    location2: "marble_100-0_y",
    location3: "wheel_25-75_b-y",
    location4: "wheel_100-0_b",
    target: "AOI1",
    competitor: "AOI2",
    condition: "usually",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "3",
    instruction3: "The |marble |usually lands on |blue.",
    trial_in_list: "12",
    variant: "V1"
  },
  {
    displayID: "11",
    location1: "marble_100-0_y",
    location2: "marble_25-75_y-g",
    location3: "wheel_100-0_y",
    location4: "wheel_25-75_y-g",
    target: "AOI3",
    competitor: "AOI4",
    condition: "always",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "3",
    instruction3: "The |arrow |always lands on |yellow.",
    trial_in_list: "13",
    variant: "V1"
  },
  {
    displayID: "11",
    location1: "marble_25-75_y-g",
    location2: "marble_100-0_y",
    location3: "wheel_25-75_y-g",
    location4: "wheel_100-0_y",
    target: "AOI1",
    competitor: "AOI2",
    condition: "rarely",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "3",
    instruction3: "The |marble |rarely lands on |yellow.",
    trial_in_list: "14",
    variant: "V1"
  },
  {
    displayID: "12",
    location1: "marble_25-75_y-g",
    location2: "marble_100-0_y",
    location3: "wheel_25-75_g-y",
    location4: "wheel_100-0_g",
    target: "AOI3",
    competitor: "AOI4",
    condition: "usually",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "3",
    instruction3: "The |arrow |usually lands on |yellow.",
    trial_in_list: "15",
    variant: "V1"
  },
  {
    displayID: "12",
    location1: "marble_100-0_y",
    location2: "marble_25-75_y-g",
    location3: "wheel_100-0_g",
    location4: "wheel_25-75_g-y",
    target: "AOI1",
    competitor: "AOI2",
    condition: "never",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "3",
    instruction3: "The |marble |never lands on |green.",
    trial_in_list: "16",
    variant: "V1"
  },
  {
    displayID: "3",
    location1: "marble_25-75_g-b",
    location2: "marble_100-0_g",
    location3: "wheel_25-75_g-b",
    location4: "wheel_100-0_g",
    target: "AOI4",
    competitor: "AOI3",
    condition: "0",
    ExpFiller: "filler",
    correctAns: "AOI4",
    list: "3",
    instruction3: "The |arrow |has a 0 percent chance of landing on |blue.",
    trial_in_list: "17",
    variant: "V1"
  },
  {
    displayID: "3",
    location1: "marble_100-0_g",
    location2: "marble_25-75_g-b",
    location3: "wheel_100-0_g",
    location4: "wheel_25-75_g-b",
    target: "AOI1",
    competitor: "AOI2",
    condition: "0",
    ExpFiller: "filler",
    correctAns: "AOI1",
    list: "3",
    instruction3: "The |marble |has a 0 percent chance of landing on |blue.",
    trial_in_list: "18",
    variant: "V1"
  },
  {
    displayID: "7",
    location1: "wheel_100-0_y",
    location2: "wheel_25-75_y-b",
    location3: "marble_100-0_y",
    location4: "marble_25-75_y-b",
    target: "AOI2",
    competitor: "AOI1",
    condition: "25",
    ExpFiller: "filler",
    correctAns: "AOI2",
    list: "3",
    instruction3: "The |arrow |has a 25 percent chance of landing on |yellow.",
    trial_in_list: "19",
    variant: "V1"
  },
  {
    displayID: "7",
    location1: "wheel_25-75_y-b",
    location2: "wheel_100-0_y",
    location3: "marble_25-75_y-b",
    location4: "marble_100-0_y",
    target: "AOI3",
    competitor: "AOI4",
    condition: "25",
    ExpFiller: "filler",
    correctAns: "AOI3",
    list: "3",
    instruction3: "The |marble |has a 25 percent chance of landing on |yellow.",
    trial_in_list: "20",
    variant: "V1"
  },
  {
    displayID: "9",
    location1: "marble_100-0_g",
    location2: "marble_25-75_g-y",
    location3: "wheel_100-0_g",
    location4: "wheel_25-75_g-y",
    target: "AOI4",
    competitor: "AOI3",
    condition: "75",
    ExpFiller: "filler",
    correctAns: "AOI4",
    list: "3",
    instruction3: "The |arrow |has a 75 percent chance of landing on |yellow.",
    trial_in_list: "21",
    variant: "V1"
  },
  {
    displayID: "9",
    location1: "marble_100-0_g",
    location2: "marble_25-75_g-y",
    location3: "wheel_100-0_g",
    location4: "wheel_25-75_g-y",
    target: "AOI2",
    competitor: "AOI1",
    condition: "75",
    ExpFiller: "filler",
    correctAns: "AOI2",
    list: "3",
    instruction3: "The |marble |has a 75 percent chance of landing on |yellow.",
    trial_in_list: "22",
    variant: "V1"
  },
  {
    displayID: "10",
    location1: "wheel_100-0_y",
    location2: "wheel_25-75_y-g",
    location3: "marble_100-0_g",
    location4: "marble_25-75_g-y",
    target: "AOI1",
    competitor: "AOI2",
    condition: "100",
    ExpFiller: "filler",
    correctAns: "AOI1",
    list: "3",
    instruction3: "The |arrow |has a 100 percent chance of landing on |yellow.",
    trial_in_list: "23",
    variant: "V1"
  },
  {
    displayID: "10",
    location1: "wheel_100-0_y",
    location2: "wheel_25-75_y-g",
    location3: "marble_100-0_g",
    location4: "marble_25-75_g-y",
    target: "AOI3",
    competitor: "AOI4",
    condition: "100",
    ExpFiller: "filler",
    correctAns: "AOI3",
    list: "3",
    instruction3: "The |marble |has a 100 percent chance of landing on |green.",
    trial_in_list: "24",
    variant: "V1"
  },
  {
    displayID: "13",
    location1: "wheel_25-75_b-g",
    location2: "wheel_25-75_g-b",
    location3: "marble_100-0_b",
    location4: "marble_100-0_g",
    target: "AOI1",
    competitor: "AOI2",
    condition: "25",
    ExpFiller: "typeB",
    correctAns: "AOI1",
    list: "3",
    instruction3: "The |arrow |has a 25 percent chance of landing on |blue.",
    trial_in_list: "25",
    variant: "V1"
  },
  {
    displayID: "14",
    location1: "wheel_100-0_b",
    location2: "wheel_100-0_g",
    location3: "marble_25-75_b-g",
    location4: "marble_25-75_g-b",
    target: "AOI3",
    competitor: "AOI4",
    condition: "25",
    ExpFiller: "typeB",
    correctAns: "AOI3",
    list: "3",
    instruction3: "The |marble |has a 25 percent chance of landing on |blue.",
    trial_in_list: "26",
    variant: "V1"
  },
  {
    displayID: "15",
    location1: "wheel_25-75_b-g",
    location2: "wheel_25-75_g-b",
    location3: "marble_100-0_b",
    location4: "marble_100-0_g",
    target: "AOI1",
    competitor: "AOI2",
    condition: "75",
    ExpFiller: "typeB",
    correctAns: "AOI1",
    list: "3",
    instruction3: "The |arrow |has a 75 percent chance of landing on |green.",
    trial_in_list: "27",
    variant: "V1"
  },
  {
    displayID: "16",
    location1: "wheel_100-0_y",
    location2: "wheel_100-0_b",
    location3: "marble_25-75_y-b",
    location4: "marble_25-75_b-y",
    target: "AOI4",
    competitor: "AOI3",
    condition: "75",
    ExpFiller: "typeB",
    correctAns: "AOI4",
    list: "3",
    instruction3: "The |marble |has a 75 percent chance of landing on |yellow.",
    trial_in_list: "28",
    variant: "V1"
  },
  {
    displayID: "17",
    location1: "wheel_100-0_y",
    location2: "wheel_100-0_b",
    location3: "marble_25-75_y-b",
    location4: "marble_25-75_b-y",
    target: "AOI2",
    competitor: "AOI1",
    condition: "100",
    ExpFiller: "typeB",
    correctAns: "AOI2",
    list: "3",
    instruction3: "The |arrow |has a 100 percent chance of landing on |blue.",
    trial_in_list: "29",
    variant: "V1"
  },
  {
    displayID: "18",
    location1: "wheel_25-75_g-y",
    location2: "wheel_25-75_y-g",
    location3: "marble_100-0_g",
    location4: "marble_100-0_y",
    target: "AOI3",
    competitor: "AOI4",
    condition: "100",
    ExpFiller: "typeB",
    correctAns: "AOI3",
    list: "3",
    instruction3: "The |marble |has a 100 percent chance of landing on |green.",
    trial_in_list: "30",
    variant: "V1"
  },
  {
    displayID: "19",
    location1: "wheel_100-0_y",
    location2: "wheel_100-0_b",
    location3: "marble_25-75_y-b",
    location4: "marble_25-75_b-y",
    target: "AOI2",
    competitor: "AOI1",
    condition: "0",
    ExpFiller: "typeB",
    correctAns: "AOI2",
    list: "3",
    instruction3: "The |arrow |has a 0 percent chance of landing on |yellow.",
    trial_in_list: "31",
    variant: "V1"
  },
  {
    displayID: "20",
    location1: "wheel_25-75_y-g",
    location2: "wheel_25-75_g-y",
    location3: "marble_100-0_y",
    location4: "marble_100-0_g",
    target: "AOI4",
    competitor: "AOI3",
    condition: "0",
    ExpFiller: "typeB",
    correctAns: "AOI4",
    list: "3",
    instruction3: "The |marble |has a 0 percent chance of landing on |yellow.",
    trial_in_list: "32",
    variant: "V1"
  }
];
