exp.practice = [
    {	displayID: "1",
        location1: "vase_2-3_p-b",
        location2: "vase_5_b",
        location3: "basket_5_p",
        location4: "basket_2-3_p-b",
        target: "4",
        competitor: "3",
        condition: "prac",
        modal: "some",
        ExpFiller: "prac",
        correctAns: "AOI4",
        list:"3",
        instruction1: "In the |basket, |some of the flowers are |blue."
    },
    {	displayID: "2",
        location1: "basket_5_p",
        location2: "basket_2-3_y-p",
        location3: "vase_2-3_p-y",
        location4: "vase_5_p",
        target: "3",
        competitor: "4",
        condition: "prac",
        modal: "two",
        ExpFiller: "prac",
        correctAns: "AOI3",
        list:"3",
        instruction1: "In the |vase, |two of the flowers are |pink."
    },
    {	displayID: "3",
        location1: "basket_5_b",
        location2: "basket_5_y",
        location3: "vase_2-3_b-y",
        location4: "vase_2-3_y-b",
        target: "2",
        competitor: "1",
        condition: "prac",
        modal: "five",
        ExpFiller: "prac",
        correctAns: "AOI2",
        list:"3",
        instruction1: "In the |basket, |five of the flowers are |yellow."
    },
    {	displayID: "4",
        location1: "vase_5_b",
        location2: "vase_2-3_b-p",
        location3: "basket_5_p",
        location4: "basket_2-3_b-p",
        target: "1",
        competitor: "2",
        condition: "prac",
        modal: "none",
        ExpFiller: "prac",
        correctAns: "AOI1",
        list:"3",
        instruction1: "In the |vase, |none of the flowers are |pink."
    },
   ];

exp.stims =  [
    {	displayID: "6",
        location1: "basket_5_b",
        location2: "basket_2-3_p-b",
        location3: "vase_5_b",
        location4: "vase_2-3_p-b",
        target: "1",
        competitor: "2",
        condition: "prag",
        modal: "all",
        ExpFiller: "Exp",
        correctAns: "AOI1",
        list:"3",
        instruction3: "In the |basket, |all of the flowers are |blue."
    },
    {	displayID: "1",
        location1: "basket_2-3_y-b",
        location2: "basket_5_y",
        location3: "vase_2-3_y-b",
        location4: "vase_5_y",
        target: "2",
        competitor: "1",
        condition: "prag",
        modal: "all",
        ExpFiller: "Exp",
        correctAns: "AOI2",
        list:"3",
        instruction3: "In the |basket, |all of the flowers are |yellow."
    },
    {	displayID: "4",
        location1: "basket_5_y",
        location2: "basket_2-3_b-y",
        location3: "vase_5_y",
        location4: "vase_2-3_b-y",
        target: "3",
        competitor: "4",
        condition: "prag",
        modal: "all",
        ExpFiller: "Exp",
        correctAns: "AOI3",
        list:"3",
        instruction3: "In the |vase, |all of the flowers are |yellow."
    },
    {	displayID: "23",
        location1: "basket_2-3_y-p",
        location2: "basket_5_y",
        location3: "vase_2-3_p-y",
        location4: "vase_5_p",
        target: "4",
        competitor: "3",
        condition: "prag",
        modal: "all",
        ExpFiller: "Exp",
        correctAns: "AOI4",
        list:"3",
        instruction3: "In the |vase, |all of the flowers are |pink."
    },
    {	displayID: "17",
        location1: "vase_5_b",
        location2: "vase_2-3_b-p",
        location3: "basket_5_p",
        location4: "basket_2-3_p-b",
        target: "1",
        competitor: "2",
        condition: "prag",
        modal: "none",
        ExpFiller: "Exp",
        correctAns: "AOI1",
        list:"3",
        instruction3: "In the |vase, |none of the flowers are |pink."
    },
    {	displayID: "10",
        location1: "vase_2-3_p-y",
        location2: "vase_5_y",
        location3: "basket_5_y",
        location4: "basket_2-3_p-y",
        target: "3",
        competitor: "4",
        condition: "prag",
        modal: "none",
        ExpFiller: "Exp",
        correctAns: "AOI3",
        list:"3",
        instruction3: "In the |basket, |none of the flowers are |pink."
    },
        {	displayID: "3",
        location1: "basket_2-3_b-y",
        location2: "basket_5_b",
        location3: "vase_2-3_b-y",
        location4: "vase_5_b",
        target: "2",
        competitor: "1",
        condition: "prag",
        modal: "none",
        ExpFiller: "Exp",
        correctAns: "AOI2",
        list:"3",
        instruction3: "In the |basket, |none of the flowers are |yellow."
    },
    {	displayID: "22",
        location1: "basket_5_y",
        location2: "basket_2-3_p-y",
        location3: "vase_2-3_y-p",
        location4: "vase_5_p",
        target: "4",
        competitor: "3",
        condition: "prag",
        modal: "none",
        ExpFiller: "Exp",
        correctAns: "AOI4",
        list:"3",
        instruction3: "In the |vase, |none of the flowers are |yellow."
    },
    {	displayID: "7",
        location1: "basket_2-3_b-p",
        location2: "basket_5_b",
        location3: "vase_5_b",
        location4: "vase_2-3_b-p",
        target: "4",
        competitor: "3",
        condition: "prag",
        modal: "not all",
        ExpFiller: "Exp",
        correctAns: "AOI4",
        list:"3",
        instruction3: "In the |vase, |not all of the flowers are |blue."
    },
    {	displayID: "14",
        location1: "basket_5_b",
        location2: "basket_2-3_y-b",
        location3: "vase_5_y",
        location4: "vase_2-3_b-y",
        target: "2",
        competitor: "1",
        condition: "prag",
        modal: "not all",
        ExpFiller: "Exp",
        correctAns: "AOI2",
        list:"3",
        instruction3: "In the |basket, |not all of the flowers are |yellow."
    },
    {	displayID: "18",
        location1: "vase_5_p",
        location2: "vase_2-3_b-p",
        location3: "basket_2-3_p-b",
        location4: "basket_5_b",
        target: "3",
        competitor: "4",
        condition: "prag",
        modal: "not all",
        ExpFiller: "Exp",
        correctAns: "AOI3",
        list:"3",
        instruction3: "In the |basket, |not all of the flowers are |pink."
    },
    {	displayID: "9",
        location1: "vase_2-3_p-y",
        location2: "vase_5_p",
        location3: "basket_2-3_p-y",
        location4: "basket_5_p",
        target: "1",
        competitor: "2",
        condition: "prag",
        modal: "not all",
        ExpFiller: "Exp",
        correctAns: "AOI1",
        list:"3",
        instruction3: "In the |vase, |not all of the flowers are |pink."
    },
    {	displayID: "2",
        location1: "vase_2-3_y-b",
        location2: "vase_5_b",
        location3: "basket_5_b",
        location4: "basket_2-3_y-b",
        target: "1",
        competitor: "2",
        condition: "prag",
        modal: "some",
        ExpFiller: "Exp",
        correctAns: "AOI1",
        list:"3",
        instruction3: "In the |vase, |some of the flowers are |yellow."
    },
    {	displayID: "15",
        location1: "vase_5_y",
        location2: "vase_2-3_y-b",
        location3: "basket_2-3_b-y",
        location4: "basket_5_b",
        target: "2",
        competitor: "1",
        condition: "prag",
        modal: "some",
        ExpFiller: "Exp",
        correctAns: "AOI2",
        list:"3",
        instruction3: "In the |vase, |some of the flowers are |blue."
    },
    {	displayID: "5",
        location1: "vase_5_p",
        location2: "vase_2-3_y-p",
        location3: "basket_5_p",
        location4: "basket_2-3_y-p",
        target: "4",
        competitor: "3",
        condition: "prag",
        modal: "some",
        ExpFiller: "Exp",
        correctAns: "AOI3",
        list:"3",
        instruction3: "In the |basket, |some of the flowers are |yellow."
    },
    {	displayID: "21",
        location1: "vase_2-3_y-p",
        location2: "vase_5_y",
        location3: "basket_2-3_p-y",
        location4: "basket_5_p",
        target: "3",
        competitor: "4",
        condition: "prag",
        modal: "some",
        ExpFiller: "Exp",
        correctAns: "AOI3",
        list:"3",
        instruction3: "In the |basket, |some of the flowers are |pink."
    },
    {	displayID: "24",
        location1: "basket_5_p",
        location2: "basket_2-3_y-p",
        location3: "vase_5_y",
        location4: "vase_2-3_p-y",
        target: "4",
        competitor: "3",
        condition: "prag",
        modal: "two",
        ExpFiller: "Filler",
        correctAns: "AOI4",
        list:"3",
        instruction3: "In the |vase, |two of the flowers are |pink."
    },
    {	displayID: "19",
        location1: "basket_5_b",
        location2: "basket_2-3_b-p",
        location3: "vase_2-3_p-b",
        location4: "vase_5_p",
        target: "2",
        competitor: "1",
        condition: "prag",
        modal: "three",
        ExpFiller: "Filler",
        correctAns: "AOI2",
        list:"3",
        instruction3: "In the |basket, |three of the flowers are |pink."
    },
    {	displayID: "20",
        location1: "basket_2-3_b-p",
        location2: "basket_5_p",
        location3: "vase_2-3_p-b",
        location4: "vase_5_b",
        target: "3",
        competitor: "4",
        condition: "prag",
        modal: "three",
        ExpFiller: "Filler",
        correctAns: "AOI4",
        list:"3",
        instruction3: "In the |vase, |three of the flowers are |blue."
    },
   {	displayID: "12",
        location1: "basket_2-3_p-b",
        location2: "basket_5_p",
        location3: "vase_5_p",
        location4: "vase_2-3_p-b",
        target: "2",
        competitor: "1",
        condition: "prag",
        modal: "zero",
        ExpFiller: "Filler",
        correctAns: "AOI2",
        list:"3",
        instruction3: "In the |basket, |zero of the flowers are |blue."
    },
    {	displayID: "11",
        location1: "vase_2-3_y-p",
        location2: "vase_5_y",
        location3: "basket_5_y",
        location4: "basket_2-3_y-p",
        target: "1",
        competitor: "2",
        condition: "prag",
        modal: "two",
        ExpFiller: "Filler",
        correctAns: "AOI1",
        list:"3",
        instruction3: "In the |vase, |two of the flowers are |yellow."
    },
    {	displayID: "13",
        location1: "vase_2-3_b-y",
        location2: "vase_5_b",
        location3: "basket_5_y",
        location4: "basket_2-3_y-b",
        target: "3",
        competitor: "4",
        condition: "prag",
        modal: "zero",
        ExpFiller: "Filler",
        correctAns: "AOI3",
        list:"3",
        instruction3: "In the |basket, |zero of the flowers are |blue."
    },
    {	displayID: "8",
        location1: "vase_5_p",
        location2: "vase_2-3_b-p",
        location3: "basket_2-3_b-p",
        location4: "basket_5_p",
        target: "4",
        competitor: "3",
        condition: "prag",
        modal: "five",
        ExpFiller: "Filler",
        correctAns: "AOI4",
        list:"3",
        instruction3: "In the |basket, |five of the flowers are |pink."
    },
    {	displayID: "16",
        location1: "vase_5_b",
        location2: "vase_2-3_y-b",
        location3: "basket_2-3_b-y",
        location4: "basket_5_y",
        target: "1",
        competitor: "2",
        condition: "prag",
        modal: "five",
        ExpFiller: "Filler",
        correctAns: "AOI1",
        list:"3",
        instruction3: "In the |vase, |five of the flowers are |blue."
    },

    {	displayID: "25",
        location1: "vase_2-3_p-y",
        location2: "vase_2-3_y-p",
        location3: "basket_5_p",
        location4: "basket_5_y",
        target: "3",
        competitor: "4",
        condition: "late",
        modal: "zero",
        ExpFiller: "Filler",
        correctAns: "AOI3",
        list:"3",
        instruction3: "In the |basket, |zero of the flowers |are yellow."
    },
    {	displayID: "26",
        location1: "vase_5_b",
        location2: "vase_5_p",
        location3: "basket_2-3_b-p",
        location4: "basket_2-3_p-b",
        target: "1",
        competitor: "2",
        condition: "late",
        modal: "zero",
        ExpFiller: "Filler",
        correctAns: "AOI1",
        list:"3",
        instruction3: "In the |vase, |zero of the flowers |are pink."
    },
   {	displayID: "27",
        location1: "vase_5_p",
        location2: "vase_5_b",
        location3: "basket_2-3_p-b",
        location4: "basket_2-3_b-p",
        target: "4",
        competitor: "3",
        condition: "late",
        modal: "two",
        ExpFiller: "Filler",
        correctAns: "AOI4",
        list:"3",
        instruction3: "In the |basket, |two of the flowers are |blue."
    },
    {	displayID: "28",
        location1: "vase_2-3_y-p",
        location2: "vase_2-3_p-y",
        location3: "basket_5_p",
        location4: "basket_5_y",
        target: "2",
        competitor: "1",
        condition: "late",
        modal: "two",
        ExpFiller: "Filler",
        correctAns: "AOI2",
        list:"3",
        instruction3: "In the |vase, |two of the flowers are |pink."
    },
    {	displayID: "29",
        location1: "basket_2-3_y-p",
        location2: "basket_2-3_p-y",
        location3: "vase_5_y",
        location4: "vase_5_p",
        target: "1",
        competitor: "2",
        condition: "late",
        modal: "three",
        ExpFiller: "Filler",
        correctAns: "AOI1",
        list:"3",
        instruction3: "In the |basket, |three of the flowers are |pink."
    },
    {	displayID: "30",
        location1: "basket_5_b",
        location2: "basket_5_y",
        location3: "vase_2-3_y-b",
        location4: "vase_2-3_b-y",
        target: "4",
        competitor: "3",
        condition: "late",
        modal: "three",
        ExpFiller: "Filler",
        correctAns: "AOI4",
        list:"3",
        instruction3: "In the |vase, |three of the flowers are |yellow."
    },
    {	displayID: "31",
        location1: "basket_5_b",
        location2: "basket_5_y",
        location3: "vase_2-3_y-b",
        location4: "vase_2-3_b-y",
        target: "2",
        competitor: "1",
        condition: "late",
        modal: "five",
        ExpFiller: "Filler",
        correctAns: "AOI2",
        list:"3",
        instruction3: "In the |basket, |five of the flowers are |yellow."
    },
    {	displayID: "32",
        location1: "basket_2-3_b-p",
        location2: "basket_2-3_p-b",
        location3: "vase_5_b",
        location4: "vase_5_p",
        target: "3",
        competitor: "4",
        condition: "late",
        modal: "five",
        ExpFiller: "Filler",
        correctAns: "AOI3",
        list:"3",
        instruction3: "In the |vase, |five of the flowers are |blue."
    }


];
