
exp.practice = [
    {	displayID: "1",
        location1: "vase_2-3_p-b",
        location2: "vase_5_b",
        location3: "basket_5_b",
        location4: "basket_2-3_p-b",
        target: "4",
        competitor: "3",
        condition: "prac",
        modal: "some",
        ExpFiller: "prac",
        correctAns: "AOI4",
        list: "1",
        instruction1: "In the |basket, |some of the flowers are |pink"
    },
    {	displayID: "2",
        location1: "basket_5_y",
        location2: "basket_2-3_y-p",
        location3: "vase_2-3_p-y",
        location4: "vase_5_p",
        target: "3",
        competitor: "4",
        condition: "prac",
        modal: "two",
        ExpFiller: "prac",
        correctAns: "AOI3",
        list: "1",
        instruction1: "In the |vase, |three of the flowers are |yellow"
    },
    {	displayID: "3",
        location1: "basket_5_b",
        location2: "basket_5_y",
        location3: "vase_2-3_b-y",
        location4: "vase_2-3_y-b",
        target: "2",
        competitor: "1",
        condition: "prac",
        modal: "five",
        ExpFiller: "prac",
        correctAns: "AOI2",
        list: "1",
        instruction1: "In the |basket, |five of the flowers are |yellow."
    },
    {	displayID: "4",
        location1: "vase_5_p",
        location2: "vase_2-3_b-p",
        location3: "basket_5_p",
        location4: "basket_2-3_b-p",
        target: "1",
        competitor: "2",
        condition: "prac",
        modal: "none",
        ExpFiller: "prac",
        correctAns: "AOI1",
        list: "1",
        instruction1: "In the |vase, |none of the flowers are |blue."
    },
   ];

exp.stims = [
  {
    displayID: "6",
    location1: "basket_2-3_p-b",
    location2: "basket_5_b",
    location3: "vase_2-3_b-p",
    location4: "vase_5_p",
    target: "AOI2",
    competitor: "AOI1",
    condition: "none",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "In the |basket, |none of the flowers are |pink.",
    trial_in_list: "1",
    variant: "V1"
  },
  {
    displayID: "6",
    location1: "basket_2-3_p-b",
    location2: "basket_5_b",
    location3: "vase_2-3_b-p",
    location4: "vase_5_b",
    target: "AOI3",
    competitor: "AOI4",
    condition: "some",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "4",
    instruction3: "In the |vase, |some of the flowers are |pink.",
    trial_in_list: "2",
    variant: "V1"
  },
  {
    displayID: "2",
    location1: "basket_2-3_y-b",
    location2: "basket_5_b",
    location3: "vase_2-3_b-y",
    location4: "vase_5_y",
    target: "AOI2",
    competitor: "AOI1",
    condition: "all",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "In the |basket, |all of the flowers are |blue.",
    trial_in_list: "3",
    variant: "V1"
  },
  {
    displayID: "2",
    location1: "vase_5_b",
    location2: "vase_2-3_b-y",
    location3: "basket_5_b",
    location4: "basket_2-3_y-b",
    target: "AOI2",
    competitor: "AOI1",
    condition: "notall",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "In the |vase, |not all of the flowers are |blue.",
    trial_in_list: "4",
    variant: "V1"
  },
  {
    displayID: "10",
    location1: "vase_5_p",
    location2: "vase_2-3_y-p",
    location3: "basket_5_p",
    location4: "basket_2-3_p-y",
    target: "AOI4",
    competitor: "AOI3",
    condition: "some",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "4",
    instruction3: "In the |basket, |some of the flowers are |yellow.",
    trial_in_list: "5",
    variant: "V1"
  },
  {
    displayID: "10",
    location1: "vase_5_p",
    location2: "vase_2-3_y-p",
    location3: "basket_5_y",
    location4: "basket_2-3_p-y",
    target: "AOI1",
    competitor: "AOI2",
    condition: "none",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "4",
    instruction3: "In the |vase, |none of the flowers are |yellow.",
    trial_in_list: "6",
    variant: "V1"
  },
  {
    displayID: "7",
    location1: "basket_2-3_p-b",
    location2: "basket_5_b",
    location3: "vase_2-3_p-b",
    location4: "vase_5_b",
    target: "AOI1",
    competitor: "AOI2",
    condition: "notall",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "4",
    instruction3: "In the |basket, |not all of the flowers are |blue.",
    trial_in_list: "7",
    variant: "V1"
  },
  {
    displayID: "7",
    location1: "basket_2-3_p-b",
    location2: "basket_5_b",
    location3: "vase_2-3_p-b",
    location4: "vase_5_b",
    target: "AOI4",
    competitor: "AOI3",
    condition: "all",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "4",
    instruction3: "In the |vase, |all of the flowers are |blue.",
    trial_in_list: "8",
    variant: "V1"
  },
  {
    displayID: "5",
    location1: "vase_2-3_b-p",
    location2: "vase_5_p",
    location3: "basket_2-3_b-p",
    location4: "basket_5_p",
    target: "AOI4",
    competitor: "AOI3",
    condition: "none",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "4",
    instruction3: "In the |basket, |none of the flowers are |blue.",
    trial_in_list: "9",
    variant: "V1"
  },
  {
    displayID: "5",
    location1: "vase_2-3_b-p",
    location2: "vase_5_p",
    location3: "basket_2-3_b-p",
    location4: "basket_5_p",
    target: "AOI1",
    competitor: "AOI2",
    condition: "some",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "4",
    instruction3: "In the |vase, |some of the flowers are |blue.",
    trial_in_list: "10",
    variant: "V1"
  },
  {
    displayID: "1",
    location1: "vase_5_y",
    location2: "vase_2-3_b-y",
    location3: "basket_5_y",
    location4: "basket_2-3_b-y",
    target: "AOI3",
    competitor: "AOI4",
    condition: "all",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "4",
    instruction3: "In the |basket, |all of the flowers are |yellow.",
    trial_in_list: "11",
    variant: "V1"
  },
  {
    displayID: "1",
    location1: "basket_2-3_b-y",
    location2: "basket_5_y",
    location3: "vase_2-3_b-y",
    location4: "vase_5_b",
    target: "AOI3",
    competitor: "AOI4",
    condition: "notall",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "4",
    instruction3: "In the |vase, |not all of the flowers are |blue.",
    trial_in_list: "12",
    variant: "V1"
  },
  {
    displayID: "3",
    location1: "basket_5_b",
    location2: "basket_2-3_y-b",
    location3: "vase_5_b",
    location4: "vase_2-3_y-b",
    target: "AOI2",
    competitor: "AOI1",
    condition: "some",
    ExpFiller: "exp",
    correctAns: "AOI2",
    list: "4",
    instruction3: "In the |basket, |some of the flowers are |yellow.",
    trial_in_list: "13",
    variant: "V1"
  },
  {
    displayID: "3",
    location1: "basket_5_b",
    location2: "basket_2-3_y-b",
    location3: "vase_5_b",
    location4: "vase_2-3_y-b",
    target: "AOI3",
    competitor: "AOI4",
    condition: "none",
    ExpFiller: "exp",
    correctAns: "AOI3",
    list: "4",
    instruction3: "In the |vase, |none of the flowers are |yellow.",
    trial_in_list: "14",
    variant: "V1"
  },
  {
    displayID: "9",
    location1: "vase_5_p",
    location2: "vase_2-3_y-p",
    location3: "basket_5_p",
    location4: "basket_2-3_y-p",
    target: "AOI4",
    competitor: "AOI3",
    condition: "notall",
    ExpFiller: "exp",
    correctAns: "AOI4",
    list: "4",
    instruction3: "In the |basket, |not all of the flowers are |pink.",
    trial_in_list: "15",
    variant: "V1"
  },
  {
    displayID: "9",
    location1: "vase_5_p",
    location2: "vase_2-3_y-p",
    location3: "basket_5_p",
    location4: "basket_2-3_y-p",
    target: "AOI1",
    competitor: "AOI2",
    condition: "all",
    ExpFiller: "exp",
    correctAns: "AOI1",
    list: "4",
    instruction3: "In the |vase, |all of the flowers are |pink.",
    trial_in_list: "16",
    variant: "V1"
  },
  {
    displayID: "4",
    location1: "basket_5_y",
    location2: "basket_2-3_b-y",
    location3: "vase_5_b",
    location4: "vase_2-3_y-b",
    target: "AOI1",
    competitor: "AOI2",
    condition: "0",
    ExpFiller: "filler",
    correctAns: "AOI1",
    list: "4",
    instruction3: "In the |basket, |zero of the flowers are |blue.",
    trial_in_list: "17",
    variant: "V1"
  },
  {
    displayID: "4",
    location1: "basket_2-3_b-y",
    location2: "basket_5_y",
    location3: "vase_2-3_y-b",
    location4: "vase_5_b",
    target: "AOI4",
    competitor: "AOI3",
    condition: "0",
    ExpFiller: "filler",
    correctAns: "AOI4",
    list: "4",
    instruction3: "In the |vase, |zero of the flowers are |yellow.",
    trial_in_list: "18",
    variant: "V1"
  },
  {
    displayID: "8",
    location1: "vase_2-3_p-b",
    location2: "vase_5_b",
    location3: "basket_2-3_b-p",
    location4: "basket_5_p",
    target: "AOI3",
    competitor: "AOI4",
    condition: "2",
    ExpFiller: "filler",
    correctAns: "AOI3",
    list: "4",
    instruction3: "In the |basket, |two of the flowers are |blue.",
    trial_in_list: "19",
    variant: "V1"
  },
  {
    displayID: "8",
    location1: "vase_5_b",
    location2: "vase_2-3_p-b",
    location3: "basket_5_p",
    location4: "basket_2-3_b-p",
    target: "AOI2",
    competitor: "AOI1",
    condition: "2",
    ExpFiller: "filler",
    correctAns: "AOI2",
    list: "4",
    instruction3: "In the |vase, |two of the flowers are |pink.",
    trial_in_list: "20",
    variant: "V1"
  },
  {
    displayID: "11",
    location1: "basket_5_p",
    location2: "basket_2-3_p-y",
    location3: "vase_5_y",
    location4: "vase_2-3_p-y",
    target: "AOI2",
    competitor: "AOI1",
    condition: "3",
    ExpFiller: "filler",
    correctAns: "AOI2",
    list: "4",
    instruction3: "In the |basket, |three of the flowers are |yellow.",
    trial_in_list: "21",
    variant: "V1"
  },
  {
    displayID: "11",
    location1: "basket_5_y",
    location2: "basket_2-3_p-y",
    location3: "vase_5_p",
    location4: "vase_2-3_p-y",
    target: "AOI4",
    competitor: "AOI3",
    condition: "3",
    ExpFiller: "filler",
    correctAns: "AOI4",
    list: "4",
    instruction3: "In the |vase, |three of the flowers are |yellow.",
    trial_in_list: "22",
    variant: "V1"
  },
  {
    displayID: "12",
    location1: "vase_5_y",
    location2: "vase_2-3_p-y",
    location3: "basket_5_p",
    location4: "basket_2-3_y-p",
    target: "AOI3",
    competitor: "AOI4",
    condition: "5",
    ExpFiller: "filler",
    correctAns: "AOI3",
    list: "4",
    instruction3: "In the |basket, |five of the flowers are |pink.",
    trial_in_list: "23",
    variant: "V1"
  },
  {
    displayID: "12",
    location1: "vase_5_y",
    location2: "vase_2-3_p-y",
    location3: "basket_5_p",
    location4: "basket_2-3_y-p",
    target: "AOI1",
    competitor: "AOI2",
    condition: "5",
    ExpFiller: "filler",
    correctAns: "AOI1",
    list: "4",
    instruction3: "In the |vase, |five of the flowers are |yellow.",
    trial_in_list: "24",
    variant: "V1"
  },
  {
    displayID: "13",
    location1: "vase_2-3_y-b",
    location2: "vase_2-3_b-y",
    location3: "basket_2-3_y-b",
    location4: "basket_2-3_b-y",
    target: "AOI3",
    competitor: "AOI4",
    condition: "2",
    ExpFiller: "typeB",
    correctAns: "AOI3",
    list: "4",
    instruction3: "In the |basket, |two of the flowers are |yellow.",
    trial_in_list: "25",
    variant: "V1"
  },
  {
    displayID: "14",
    location1: "vase_2-3_b-y",
    location2: "vase_2-3_y-b",
    location3: "basket_2-3_b-y",
    location4: "basket_2-3_y-b",
    target: "AOI1",
    competitor: "AOI2",
    condition: "2",
    ExpFiller: "typeB",
    correctAns: "AOI1",
    list: "4",
    instruction3: "In the |vase, |two of the flowers are |blue.",
    trial_in_list: "26",
    variant: "V1"
  },
  {
    displayID: "15",
    location1: "basket_2-3_y-b",
    location2: "basket_2-3_b-y",
    location3: "vase_2-3_y-b",
    location4: "vase_2-3_b-y",
    target: "AOI1",
    competitor: "AOI2",
    condition: "3",
    ExpFiller: "typeB",
    correctAns: "AOI1",
    list: "4",
    instruction3: "In the |basket, |three of the flowers are |blue.",
    trial_in_list: "27",
    variant: "V1"
  },
  {
    displayID: "16",
    location1: "basket_2-3_p-b",
    location2: "basket_2-3_b-p",
    location3: "vase_2-3_p-b",
    location4: "vase_2-3_b-p",
    target: "AOI4",
    competitor: "AOI3",
    condition: "3",
    ExpFiller: "typeB",
    correctAns: "AOI4",
    list: "4",
    instruction3: "In the |vase, |three of the flowers are |pink.",
    trial_in_list: "28",
    variant: "V1"
  },
  {
    displayID: "17",
    location1: "basket_5_p",
    location2: "basket_5_b",
    location3: "vase_5_p",
    location4: "vase_5_b",
    target: "AOI2",
    competitor: "AOI1",
    condition: "5",
    ExpFiller: "typeB",
    correctAns: "AOI2",
    list: "4",
    instruction3: "In the |basket, |five of the flowers are |blue.",
    trial_in_list: "29",
    variant: "V1"
  },
  {
    displayID: "18",
    location1: "basket_5_y",
    location2: "basket_5_p",
    location3: "vase_5_y",
    location4: "vase_5_p",
    target: "AOI4",
    competitor: "AOI3",
    condition: "5",
    ExpFiller: "typeB",
    correctAns: "AOI4",
    list: "4",
    instruction3: "In the |vase, |five of the flowers are |pink.",
    trial_in_list: "30",
    variant: "V1"
  },
  {
    displayID: "19",
    location1: "vase_5_b",
    location2: "vase_5_p",
    location3: "basket_5_b",
    location4: "basket_5_p",
    target: "AOI3",
    competitor: "AOI4",
    condition: "0",
    ExpFiller: "typeB",
    correctAns: "AOI3",
    list: "4",
    instruction3: "In the |basket, |zero of the flowers are |pink.",
    trial_in_list: "31",
    variant: "V1"
  },
  {
    displayID: "20",
    location1: "vase_5_p",
    location2: "vase_5_y",
    location3: "basket_5_p",
    location4: "basket_5_y",
    target: "AOI2",
    competitor: "AOI1",
    condition: "0",
    ExpFiller: "typeB",
    correctAns: "AOI2",
    list: "4",
    instruction3: "In the |vase, |zero of the flowers are |pink.",
    trial_in_list: "32",
    variant: "V1"
  }
];
